
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/google-test-example-ruby
    steps:
      - checkout
      - save_cache:
          key: grt-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/google-test-example-ruby

  bundle_dependencies:
    working_directory: ~/google-test-example-ruby  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - grt-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - grt-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: grt-bundle-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/google-test-example-ruby/vendor/bundle
      - save_cache:
          key: grt-bundle-{{ .Branch }}
          paths: 
            - ~/google-test-example-ruby/vendor/bundle
  
  chrome_test:
    working_directory: ~/google-test-example-ruby
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          keys:
            - grt-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - grt-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios
          command: bundle exec cucumber --format pretty --format html --out=features_report.html
      - store_test_results:
          path: ~/cucumber/features_report.html
      - store_artifacts:
          path: ~/cucumber/features_report.html

workflows:
  version: 2
  build_and_test:
#    triggers:
#      - schedule:
#          cron: "* 4 * * *"
#          filters:
#            branches:
#              only: master
    jobs:
      - build
      - bundle_dependencies:
          requires: 
            - build
      - chrome_test:
          requires:
            - bundle_dependencies
