# Versão do CircleCI que estamos utilizando
version: 2

# Jobs são os passos que serão executados ao realizarmos um commit
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/temp
    
    # Neste step estamos fazendo o primeiro passo, que é o checkout, como o git clone que executamos anteriormente. 
    # Aqui também salvamos em cache o repositório para agilizar os próximos passos.
    steps:
      - checkout
      - save_cache:
          key: google-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/temp

  # Neste step vamos baixar as dependências do nosso problema, no caso, as gem's. 
  # Como no passo checkout_code, salvamos as dependências em cache, sempre pensando na otimização dos passos seguintes.
  bundle_dependencies:
    working_directory: ~/temp
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - google-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - google-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: google-bundle-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/temp/vendor/bundle
      - save_cache:
          key: google-bundle-{{ .Branch }}
          paths: 
            - ~/temp/vendor/bundle
  
  
  chrome_test:
    working_directory: ~/temp
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          keys:
            - google-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - google-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios (except @wip tags) on Goole Chrome browser
          command: |
            #mkdir /test-results
            command: |
            bundle exec cucumber --format pretty --format html --out=tmp/test-results/features_report.html
      - store_test_results:
          path: ~/temp/test-results/
      - store_artifacts:
          path: ~/temp/test-results/

# Aqui começa a mágia, que nada mais é que a configuramos do workflow
workflows:
  version: 2
  build_and_test:
    # Ao commitar, o sistema vai seguir a seguinte ordem, executando cada un dos jobs, na ordem definidada aqui.
    # No caso, ele fará o seguinte: 'checkout_code' > 'bundle_dependencies' > 'code_analyzer' > 'chrome_test'
    # Configuramos essa ordem através do atributo 'requires' dentro dos jobs abaixo.
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires: 
            - checkout_code
      - chrome_test:
          requires:
            - bundle_dependencies
